name: lacak_by_sasat
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  base:
    git:
      url: https://github.com/strhmdn14102004/assets.git
  get: 4.6.6
  dio: 5.3.2
  shared_preferences: 2.2.1
  lottie: 3.3.1
  easy_localization: 3.0.7
  smooth_corner: 1.1.1
  dotted_border: 2.1.0
  geolocator: 13.0.2
  flutter_bloc: 8.1.3
  go_router: 14.8.1
  provider: 6.1.2
  loader_overlay: 2.1.0
  shimmer: 3.0.0
  firebase_core: 3.13.0
  firebase_messaging: 15.2.5
  flutter_local_notifications: 19.2.1
  device_info_plus: 11.3.0
  equatable: 2.0.7
  flutter_svg: 2.1.0
  flutter_map: 8.1.1
  url_launcher: 6.3.1
  latlong2: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/image/
    - assets/lottie/
    - assets/i18n/
    - assets/svg/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Bold.ttf
        - asset: assets/font/Manrope-ExtraBold.ttf
        - asset: assets/font/Manrope-ExtraLight.ttf
        - asset: assets/font/Manrope-Light.ttf
        - asset: assets/font/Manrope-Medium.ttf
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-SemiBold.ttf