// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCakMpeYGO2nl5UVFmFMCIOLVjw6ST4Aog",
    appId: "1:139944539012:android:f24a5ab00f75167cfbe3d1",
    messagingSenderId: "139944539012",
    projectId: "find-my-partner-5616f",
    authDomain: "find-my-partner-5616f.firebaseapp.com",
    databaseURL:
        "https://find-my-partner-5616f-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://find-my-partner-5616f.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCakMpeYGO2nl5UVFmFMCIOLVjw6ST4Aog",
    appId: "1:139944539012:android:f7ee249f4c9ec7ddfbe3d1",
    messagingSenderId: "139944539012",
    projectId: "find-my-partner-5616f",
    authDomain: "find-my-partner-5616f.firebaseapp.com",
    databaseURL:
        "https://find-my-partner-5616f-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://find-my-partner-5616f.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: "AIzaSyCakMpeYGO2nl5UVFmFMCIOLVjw6ST4Aog",
    appId: "1:139944539012:ios:b11fc451a8390091fbe3d1",
    messagingSenderId: "139944539012",
    projectId: "find-my-partner-5616f",
    authDomain: "find-my-partner-5616f.firebaseapp.com",
    databaseURL:
        "https://find-my-partner-5616f-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://find-my-partner-5616f.appspot.com",
    iosClientId:
        "1:139944539012:ios:b11fc451a8390091fbe3d1",
    iosBundleId: "com.sasat.lacakapps",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAYph65Y8llU5XoKvnWjFqbisTQJpbvpQk",
    appId: "1:140156137344:android:d82aa26dd68d3342351b65",
    messagingSenderId: "140156137344",
    projectId: "satset-toko",
    authDomain: "satset-toko.firebaseapp.com",
    databaseURL:
        "https://satset-toko-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://satset-toko.appspot.com",
    androidClientId:
        "230688948865-7jmnmdi3a3c4811d4b3sf1s5klnnhi6n.apps.googleusercontent.com",
    iosBundleId: "com.sisapp.vireopos.RunnerTests",
  );
}